export const DEFAULT_OPTIONS = [
  '1ST FTT RECEIVED',
  '2ND FTT RECEIVED',
  '3RD FTT RECEIVED: CALL',
  //
  'AC FAIL - AREA POWER FAIL',
  'ARMED ROBBERY',
  'ATTEMPTED HOUSEBREAK',
  //
  'POSITIVE BREAK IN',
  'HIJACKING',
  'CUSTOMER CODED AIO',
  //
  'CUSTOMER INFORMED',
  'CUSTOMER REQUESTS RESPONSE',
  'ENGAGED',
  //
  'FAULTY SYSTEM/ON SPEC.ATT',
  'FRAUDULENT CHECK',
  'MONITORED',
  //
  'NO SIGN OF FORCED ENTRY',
  'RECEIVED FTT ON NIGHT SHIFT',
  'IGNORE SIGNAL AS PER CUSTOMER',
  //
  'TECHNICAL TESTING',
  'CUSTOMER TESTING',
  'TESTED ALARM WITH CUSTOMER',
];
